In [2]:
#Para instalar as bibliotecas necessárias
#%pip install geopandas
#%pip install mapclassify
# Importações das bibliotecas
# dados e geodados
import pandas as pd
import geopandas as gpd
# download de arquivos
import urllib.request
#visualização
import matplotlib.pyplot as plt
import folium
import mapclassify
#exibição dos gráficos no notebook
%matplotlib inline

In [8]:
arp = gpd.read_file('.\\SIN492 - Datasets-20230614T222923Z-001\SIN492 - Datasets\\area_preservacao.geojson')
bah = gpd.read_file('.\\SIN492 - Datasets-20230614T222923Z-001\SIN492 - Datasets\\bacia_hidrografica.geojson')
cur = gpd.read_file('.\\SIN492 - Datasets-20230614T222923Z-001\SIN492 - Datasets\\curso_dagua.geojson')
es = gpd.read_file('.\\SIN492 - Datasets-20230614T222923Z-001\SIN492 - Datasets\\estadosBR.geojson')
ma = gpd.read_file('.\\SIN492 - Datasets-20230614T222923Z-001\SIN492 - Datasets\\macroregiao.geojson')
sede = gpd.read_file('.\\SIN492 - Datasets-20230614T222923Z-001\SIN492 - Datasets\\sede_municipal.geojson')

In [22]:
sedes_juncao = sede.sjoin(df=bah, how='inner',
predicate='intersects',
lsuffix='left',
rsuffix='right')

bah_rio_doce = bah[bah['nome'] == 'Bacia do Rio Doce']

sedes_cortadas = gpd.clip(sedes_juncao, bah_rio_doce.geometry)

sedes_cortadas.shape[0]

191

In [34]:
curso_juncao_in = cur.sjoin(df=arp, how='inner',
predicate='intersects',
lsuffix='left',
rsuffix='right')

curso_juncao_wi = cur.sjoin(df=arp, how='inner',
predicate='within',
lsuffix='left',
rsuffix='right')

merged = pd.concat([curso_juncao_in, curso_juncao_wi])

# Exibir os valores únicos da coluna "nome_left"
valores_unicos = merged['nome_left'].unique()
print(valores_unicos)

['sem nome' 'Rio Mainart' 'Ribeirão Cachoeira' 'Rio Gualaxo do Sul'
 'Rio Piracicaba' 'Rio da Ponte' 'Rio do Carmo' 'Rio das Velhas'
 'Córrego Olaria' 'Rio São Francisco' 'Rio Todos-os-Santos'
 'Ribeirão do Potã' 'Córrego Mumbuca' 'Córrego São José' 'Rio Paraopeba'
 'Rio Manso' 'Rio Cipó' 'Ribeirão do Escurinho' 'Córrego Espalha'
 'Córrego Rico']

In [35]:
sede

,id,name,geocodigo_,nome_munic,uf,geometry
0,1,ALTA FLORESTA D'OESTE,1100015,ALTA FLORESTA D'OESTE,ro,POINT (-61.99982 -11.93554)
1,2,ARIQUEMES,1100023,ARIQUEMES,ro,POINT (-63.03327 -9.90846)
2,3,CABIXI,1100031,CABIXI,ro,POINT (-60.54431 -13.49976)
3,4,CACOAL,1100049,CACOAL,ro,POINT (-61.44294 -11.43387)
4,5,CEREJEIRAS,1100056,CEREJEIRAS,ro,POINT (-60.81843 -13.19503)
...,...,...,...,...,...,...
5565,5566,MOJUÍ DOS CAMPOS,1504752,MOJUÍ DOS CAMPOS,pa,POINT (-54.65062 -26.82213)
5566,5567,PESCARIA BRAVA,4212650,PESCARIA BRAVA,sc,POINT (-48.86600 -28.38671)
5567,5568,BALNEÁRIO RINCÃO,4220000,BALNEÁRIO RINCÃO,sc,POINT (-49.24067 -28.80429)
5568,5569,PINTO BANDEIRA,4314548,PINTO BANDEIRA,rs,POINT (-51.45222 -29.09692)
5569,5570,PARAÍSO DAS ÁGUAS,5006275,PARAÍSO DAS ÁGUAS,ms,POINT (-53.01307 -19.01739)